name: Keepalive Workflow

on:
  schedule:
    # Chạy vào lúc 5:30 UTC mỗi ngày (khoảng 12:30 trưa giờ Việt Nam)
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create or update a keepalive file
        run: |
          echo "This file is updated daily to keep the repository active." > keepalive.txt
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add keepalive.txt
          # Chỉ commit và push nếu có thay đổi
          git diff --staged --quiet || git commit -m "CHORE: Update keepalive file to prevent workflow suspension" && git push
